import { StyleSheet } from 'react-native';
import { fontSize, spacing, moderateScale, wp } from '../../utils/responsive';
import { borderRadius } from '../../theme/designTokens';

const styles = StyleSheet.create({
  container: {
    marginVertical: spacing.xs / 2,
    paddingHorizontal: spacing.sm,
    position: 'relative',
  },
  currentUserContainer: {
    alignItems: 'flex-end',
  },
  otherUserContainer: {
    alignItems: 'flex-start',
  },
  messageRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  avatarContainer: {
    width: moderateScale(32),
    marginRight: spacing.xs,
    marginBottom: spacing.xs / 2,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  avatarPlaceholder: {
    width: moderateScale(28),
    height: moderateScale(1),
  },
  bubbleWrapper: {
    maxWidth: '80%',
    position: 'relative',
  },
  senderName: {
    fontWeight: '600',
    marginBottom: 2,
  },
  senderNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
    gap: 4,
  },
  senderNameWithAvatar: {
    marginLeft: moderateScale(36),
  },
  repBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
    gap: 2,
  },
  repBadgeText: {
    fontSize: fontSize(9),
    fontWeight: '700',
    color: '#FFFFFF',
  },
  bubble: {
    maxWidth: moderateScale(280),
    minWidth: moderateScale(60),
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.lg,
    overflow: 'hidden',
  },
  imageBubble: {
    padding: spacing.xs / 2,
  },
  currentUserBubble: {
    borderBottomRightRadius: spacing.xs,
  },
  otherUserBubble: {
    borderBottomLeftRadius: spacing.xs,
  },
  pinnedBubble: {
    borderWidth: 1,
    borderColor: 'rgba(102, 126, 234, 0.5)',
  },
  pinnedIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xs / 2,
    gap: 2,
  },
  pinnedText: {
    fontWeight: '500',
  },
  mentionHighlight: {
    backgroundColor: 'rgba(102, 126, 234, 0.3)',
    borderRadius: 2,
    fontWeight: '600',
  },
  linkText: {
    textDecorationLine: 'underline',
    fontWeight: '500',
  },
  replyContainer: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    marginBottom: spacing.sm,
    borderLeftWidth: 3,
    borderRadius: borderRadius.sm,
    backgroundColor: 'transparent',
  },
  replyToSender: {
    fontWeight: '600',
    marginBottom: 2,
  },
  replyToContent: {
    fontWeight: '400',
  },
  messageImage: {
    width: moderateScale(180),
    height: moderateScale(180),
    borderRadius: borderRadius.md,
    marginBottom: spacing.xs / 2,
  },
  messageImageOnly: {
    marginBottom: 0,
  },
  messageText: {
    lineHeight: fontSize(14) * 1.5,
  },
  messageTextWithImage: {
    marginTop: spacing.xs,
  },
  timeText: {
    alignSelf: 'flex-end',
    marginTop: spacing.xs / 2,
  },
  swipeIndicator: {
    position: 'absolute',
    top: '50%',
    marginTop: -moderateScale(8),
    opacity: 0.3,
  },
  swipeIndicatorLeft: {
    left: spacing.xs,
  },
  swipeIndicatorRight: {
    right: spacing.xs,
  },
  timeStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: spacing.xs,
  },
  reactionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  reactionsRowLeft: {
    alignSelf: 'flex-start',
    marginLeft: moderateScale(36),
  },
  reactionsRowRight: {
    alignSelf: 'flex-end',
    marginRight: spacing.sm,
  },
  reactionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.lg,
    backgroundColor: 'rgba(0,0,0,0.08)',
  },
  reactionEmojiText: {
    fontSize: moderateScale(18),
  },
  reactionEmojiChipText: {
    fontSize: moderateScale(14),
  },
  reactionCount: {
    fontSize: fontSize(12),
    fontWeight: '600',
  },
  reactionAddCorner: {
    position: 'absolute',
    top: -moderateScale(6),
    right: -moderateScale(6),
    width: moderateScale(26),
    height: moderateScale(26),
    borderRadius: moderateScale(13),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.08)',
  },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: spacing.xs,
    paddingVertical: spacing.xs,
  },
  retryText: {
    color: '#EF4444',
    fontSize: fontSize(10),
    fontWeight: '500',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: moderateScale(50),
    right: moderateScale(20),
    zIndex: 10,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: moderateScale(18),
    padding: spacing.sm,
  },
  fullImage: {
    width: '95%',
    height: '80%',
  },
  actionsOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionsContainer: {
    width: '70%',
    maxWidth: wp(75),
    borderRadius: borderRadius.lg,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  reactionQuickRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.08)',
  },
  reactionQuickButton: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.lg,
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  reactionQuickIcon: {
    width: moderateScale(26),
    height: moderateScale(26),
    borderRadius: moderateScale(13),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.05)',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    gap: spacing.md,
  },
  actionButtonBorder: {
    borderBottomWidth: 1,
  },
  actionLabel: {
    fontWeight: '500',
  },
  reactionPickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
  },
  reactionPickerContent: {
    width: '100%',
    maxWidth: wp(70),
    borderRadius: borderRadius.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
  },
  reactionPickerTitle: {
    fontWeight: '600',
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  reactionPickerRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  userMentionText: {
    fontWeight: '600',
    textDecorationLine: 'none',
  },
  mentionPreviewOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mentionPreviewContainer: {
    width: moderateScale(220),
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  mentionPreviewHeader: {
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  mentionPreviewAvatar: {
    width: moderateScale(64),
    height: moderateScale(64),
    borderRadius: moderateScale(32),
    marginBottom: spacing.sm,
  },
  mentionPreviewAvatarPlaceholder: {
    width: moderateScale(64),
    height: moderateScale(64),
    borderRadius: moderateScale(32),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  mentionPreviewAvatarText: {
    color: '#FFFFFF',
    fontSize: moderateScale(24),
    fontWeight: '600',
  },
  mentionPreviewName: {
    fontWeight: '600',
    textAlign: 'center',
  },
  mentionPreviewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.lg,
    gap: spacing.xs,
    width: '100%',
  },
  mentionPreviewButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  searchHighlight: {
    borderRadius: 2,
    paddingHorizontal: 2,
  },
  currentSearchResult: {
    borderWidth: 2,
    borderColor: '#FFEB3B',
  },
  currentSearchResultContainer: {
    backgroundColor: 'rgba(255, 235, 59, 0.15)',
    borderRadius: borderRadius.md,
    marginHorizontal: -spacing.xs,
    paddingHorizontal: spacing.xs,
  },
  selectionCheckbox: {
    position: 'absolute',
    left: spacing.xs,
    top: spacing.sm,
    zIndex: 5,
    padding: spacing.xs,
  },
  postShareCard: {
    borderRadius: borderRadius.md,
    overflow: 'hidden',
    width: moderateScale(220),
  },
  postShareThumbnail: {
    width: '100%',
    height: moderateScale(120),
    borderRadius: borderRadius.md,
    marginBottom: spacing.xs,
  },
  postShareInfo: {
    paddingHorizontal: spacing.xs,
  },
  postShareHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs / 2,
    marginBottom: spacing.xs / 2,
  },
  postShareTitle: {
    fontWeight: '700',
    marginBottom: spacing.xs / 2,
  },
  postShareSummary: {
    fontWeight: '400',
    lineHeight: fontSize(12) * 1.4,
  },
  postShareFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs / 2,
    paddingHorizontal: spacing.xs,
    marginTop: spacing.xs,
  },
  postShareLabel: {
    fontWeight: '500',
  },
  locationCard: {
    borderRadius: borderRadius.md,
    overflow: 'hidden',
    width: moderateScale(220),
  },
  locationMapPreviewContainer: {
    width: '100%',
    height: moderateScale(140),
    borderRadius: borderRadius.md,
    overflow: 'hidden',
    backgroundColor: 'rgba(0,0,0,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationMapPreview: {
    width: '100%',
    height: moderateScale(140),
    minHeight: moderateScale(140),
  },
  locationMapOverlay: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationGradient: {
    width: '100%',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    borderRadius: borderRadius.md,
  },
  locationButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: fontSize(14),
    marginTop: spacing.xs,
  },
  locationCoords: {
    color: 'rgba(255,255,255,0.7)',
    fontWeight: '400',
    fontSize: fontSize(10),
  },
  locationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs / 2,
    marginTop: spacing.xs,
    paddingHorizontal: spacing.xs,
  },
  locationText: {
    fontWeight: '500',
  },
  locationHint: {
    fontWeight: '400',
    paddingHorizontal: spacing.xs,
    marginTop: spacing.xs / 2,
  },
  voiceCard: {
    width: moderateScale(182),
    borderRadius: borderRadius.md,
    borderWidth: 1,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
  },
  voiceTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  voicePlayButton: {
    width: moderateScale(30),
    height: moderateScale(30),
    borderRadius: moderateScale(15),
    justifyContent: 'center',
    alignItems: 'center',
  },
  voiceMetaContainer: {
    flex: 1,
    justifyContent: 'center',
    gap: spacing.xs / 2,
  },
  voiceLabel: {
    fontWeight: '700',
  },
  voiceDuration: {
    fontWeight: '500',
  },
  voiceBarsRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.xs / 4,
    minHeight: moderateScale(10),
  },
  voiceBar: {
    width: moderateScale(3),
    borderRadius: moderateScale(2),
  },
  voiceProgressTrack: {
    width: '100%',
    height: moderateScale(4),
    borderRadius: moderateScale(2),
    overflow: 'hidden',
  },
  voiceProgressFill: {
    height: '100%',
    borderRadius: moderateScale(2),
  },
  fileCard: {
    width: moderateScale(232),
    borderRadius: borderRadius.md,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  fileIconWrap: {
    width: moderateScale(36),
    height: moderateScale(36),
    borderRadius: moderateScale(18),
    justifyContent: 'center',
    alignItems: 'center',
  },
  fileInfoWrap: {
    flex: 1,
    minWidth: 0,
  },
  fileName: {
    fontWeight: '700',
  },
  fileMeta: {
    marginTop: 1,
    fontWeight: '500',
  },
  fileCaption: {
    marginTop: spacing.xs / 2,
    fontWeight: '400',
  },
  fileRightWrap: {
    alignItems: 'center',
    gap: spacing.xs,
  },
  fileTypeBadge: {
    borderWidth: 1,
    borderRadius: borderRadius.xs,
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
    fontSize: fontSize(9),
    fontWeight: '700',
    overflow: 'hidden',
  },
  pollCard: {
    width: moderateScale(220),
    borderRadius: borderRadius.md,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    gap: spacing.xs,
  },
  pollQuestion: {
    fontWeight: '700',
    fontSize: fontSize(12),
    marginBottom: spacing.xs / 2,
  },
  pollOption: {
    borderWidth: 1,
    borderRadius: borderRadius.sm,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.xs,
  },
  pollOptionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    flex: 1,
  },
  pollOptionText: {
    fontSize: fontSize(12),
    fontWeight: '500',
    flex: 1,
  },
  pollOptionPercent: {
    fontSize: fontSize(11),
    fontWeight: '600',
  },
  pollFooter: {
    marginTop: spacing.xs / 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pollMetaText: {
    fontSize: fontSize(10),
    fontWeight: '500',
  },
  gifContainer: {
    borderRadius: borderRadius.md,
    overflow: 'hidden',
    position: 'relative',
  },
  gifImage: {
    borderRadius: borderRadius.md,
    minHeight: moderateScale(80),
    maxHeight: moderateScale(300),
  },
  gifBadge: {
    position: 'absolute',
    bottom: moderateScale(6),
    left: moderateScale(6),
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderRadius: moderateScale(4),
    paddingHorizontal: moderateScale(5),
    paddingVertical: moderateScale(1),
  },
  gifBadgeText: {
    color: '#FFFFFF',
    fontSize: moderateScale(9),
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  stickerBubble: {
    backgroundColor: 'transparent',
    padding: spacing.xs,
    maxWidth: moderateScale(170),
  },
  stickerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  stickerImage: {
    minHeight: moderateScale(60),
    maxHeight: moderateScale(160),
  },
});

export default styles;
