import { StyleSheet } from 'react-native';
import { wp, spacing, fontSize, moderateScale } from '../../utils/responsive';
import { borderRadius } from '../../theme/designTokens';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
  },
  header: {
    borderBottomWidth: 1,
    paddingHorizontal: wp(4),
    paddingBottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  headerTitle: {
    fontSize: fontSize(20),
    fontWeight: '700',
    flex: 1,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  headerMenuBtn: {
    width: moderateScale(34),
    height: moderateScale(34),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: borderRadius.round,
    position: 'relative',
  },
  downloadBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: moderateScale(16),
    height: moderateScale(16),
    borderRadius: moderateScale(8),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  downloadBadgeText: {
    color: '#FFFFFF',
    fontSize: fontSize(9),
    fontWeight: '700',
  },
  content: {
    padding: spacing.sm,
    paddingBottom: spacing.xxl,
  },
  sectionTitle: {
    fontSize: fontSize(14),
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  statCard: {
    width: '31.8%',
    borderWidth: 1,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.xs,
    alignItems: 'center',
  },
  statValue: {
    fontSize: fontSize(15),
    fontWeight: '700',
  },
  statLabel: {
    marginTop: 2,
    fontSize: fontSize(10),
    textAlign: 'center',
  },
  joinBtn: {
    borderRadius: borderRadius.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  joinBtnText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: fontSize(13),
  },
  actionRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    marginBottom: spacing.sm,
    flexWrap: 'wrap',
  },
  smallBtn: {
    borderWidth: 1,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  smallBtnText: {
    fontWeight: '600',
    fontSize: fontSize(12),
  },
  card: {
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    padding: spacing.sm,
    marginBottom: spacing.sm,
  },
  cardTitle: {
    fontSize: fontSize(14),
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  composeToggleBtn: {
    borderWidth: 1,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  input: {
    borderWidth: 1,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.sm,
    fontSize: fontSize(12),
  },
  stageSuggestionWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  stageSuggestionChip: {
    borderWidth: 1,
    borderRadius: borderRadius.round,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  stageSuggestionChipText: {
    fontSize: fontSize(10),
    fontWeight: '700',
  },
  managerInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  managerInput: {
    flex: 1,
    marginBottom: 0,
  },
  managerAddButton: {
    width: moderateScale(42),
    height: moderateScale(42),
    borderWidth: 1,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  managerSuggestionsWrap: {
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
  },
  managerSuggestionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
  },
  multiline: {
    minHeight: moderateScale(82),
    textAlignVertical: 'top',
  },
  typeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  typeChip: {
    borderWidth: 1,
    borderRadius: borderRadius.round,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  typeChipText: {
    fontSize: fontSize(11),
    fontWeight: '700',
  },
  fileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  fileName: {
    flex: 1,
    fontSize: fontSize(11),
  },
  uploadBtn: {
    borderRadius: borderRadius.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  uploadBtnText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: fontSize(12),
  },
  uploadError: {
    marginTop: spacing.sm,
    fontSize: fontSize(11),
  },
  infoText: {
    fontSize: fontSize(12),
  },
  assetCard: {
    borderWidth: 1,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
    marginBottom: spacing.sm,
  },
  assetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  assetTitle: {
    flex: 1,
    fontSize: fontSize(13),
    fontWeight: '700',
  },
  assetType: {
    fontSize: fontSize(10),
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  assetDescription: {
    fontSize: fontSize(12),
    marginTop: spacing.xs,
  },
  previewContainer: {
    marginTop: spacing.xs,
    marginBottom: spacing.xs,
    borderWidth: 1,
    borderRadius: borderRadius.md,
    overflow: 'hidden',
  },
  filePreviewContainer: {
    minHeight: moderateScale(68),
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  linkPreviewContainer: {
    minHeight: moderateScale(62),
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  youtubePreviewContainer: {
    minHeight: moderateScale(96),
  },
  youtubeThumb: {
    width: '100%',
    height: moderateScale(132),
  },
  youtubeBlockedBadge: {
    position: 'absolute',
    left: spacing.xs,
    right: spacing.xs,
    bottom: spacing.xs,
    borderRadius: borderRadius.round,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  youtubeBlockedText: {
    fontSize: fontSize(10),
    fontWeight: '700',
  },
  previewOverlayRow: {
    position: 'absolute',
    top: spacing.xs,
    left: spacing.xs,
    right: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.xs,
  },
  previewBadge: {
    borderWidth: 1,
    borderRadius: borderRadius.round,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  previewBadgeText: {
    fontSize: fontSize(10),
    fontWeight: '700',
  },
  previewPlayButton: {
    borderWidth: 1,
    borderRadius: borderRadius.round,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  previewPlayText: {
    fontSize: fontSize(10),
    fontWeight: '700',
  },
  youtubePlayerWrap: {
    borderTopWidth: 1,
    paddingTop: spacing.xs,
  },
  youtubeExternalBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderRadius: borderRadius.md,
    marginBottom: spacing.xs,
  },
  youtubeExternalText: {
    fontSize: fontSize(12),
    fontWeight: '700',
  },
  youtubeInlineThumb: {
    width: '100%',
    height: moderateScale(160),
    borderRadius: borderRadius.md,
  },
  fileExtBadge: {
    minWidth: moderateScale(48),
    height: moderateScale(34),
    borderRadius: borderRadius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
  },
  fileExtText: {
    color: '#FFFFFF',
    fontSize: fontSize(10),
    fontWeight: '800',
  },
  linkIconWrap: {
    width: moderateScale(34),
    height: moderateScale(34),
    borderRadius: borderRadius.round,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewMetaColumn: {
    flex: 1,
  },
  previewMetaTitle: {
    fontSize: fontSize(11),
    fontWeight: '700',
  },
  previewMetaSubtitle: {
    marginTop: 1,
    fontSize: fontSize(10),
  },
  folderHeaderRow: {
    borderWidth: 1,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    marginBottom: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  folderHeaderText: {
    fontSize: fontSize(12),
    fontWeight: '800',
  },
  assetStatsCompact: {
    marginTop: spacing.xs,
  },
  assetStatsWrap: {
    marginTop: spacing.sm,
  },
  assetStatsLabel: {
    fontSize: fontSize(10),
    marginBottom: 2,
  },
  assetStatsNames: {
    fontSize: fontSize(10),
    marginTop: 1,
  },
  assetActionsRow: {
    marginTop: spacing.sm,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pinnedLabel: {
    fontSize: fontSize(11),
    fontWeight: '700',
  },
  pinBtn: {
    borderWidth: 1,
    borderRadius: borderRadius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  pinBtnText: {
    fontSize: fontSize(11),
    fontWeight: '700',
  },
  emptyWrap: {
    paddingVertical: spacing.xl,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: fontSize(12),
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: wp(5),
  },
  modalCard: {
    borderWidth: 1,
    borderRadius: borderRadius.xl,
    padding: spacing.md,
    maxHeight: '86%',
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  modalTitle: {
    fontSize: fontSize(16),
    fontWeight: '700',
  },
  modalSectionTitle: {
    fontSize: fontSize(13),
    fontWeight: '700',
    marginBottom: spacing.xs,
    marginTop: spacing.xs,
  },
  downloadsSection: {
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
  },
  downloadRow: {
    borderWidth: 1,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    marginBottom: spacing.xs,
  },
  downloadRowTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  downloadFileName: {
    flex: 1,
    fontSize: fontSize(12),
    fontWeight: '700',
  },
  downloadPercent: {
    fontSize: fontSize(11),
    fontWeight: '700',
  },
  downloadMeta: {
    fontSize: fontSize(10),
    fontWeight: '600',
  },
  downloadProgressTrack: {
    width: '100%',
    height: moderateScale(6),
    borderRadius: borderRadius.round,
    overflow: 'hidden',
  },
  downloadProgressFill: {
    height: '100%',
  },
  downloadActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  toggleRow: {
    borderWidth: 1,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  toggleText: {
    fontSize: fontSize(12),
    fontWeight: '600',
    flex: 1,
    marginRight: spacing.sm,
  },
  optionCard: {
    borderWidth: 1,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    marginBottom: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  optionMeta: {
    flex: 1,
  },
  optionText: {
    fontSize: fontSize(12),
    fontWeight: '600',
  },
  optionSubText: {
    marginTop: 2,
    fontSize: fontSize(11),
  },
  unlinkBtn: {
    borderWidth: 1,
    borderRadius: borderRadius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  unlinkBtnText: {
    fontSize: fontSize(11),
    fontWeight: '700',
  },
  managerErrorText: {
    marginTop: spacing.xs,
    fontSize: fontSize(11),
  },
  managerStatusText: {
    marginTop: spacing.xs,
    fontSize: fontSize(11),
  },
  nameListWrap: {
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
  },
  managerIdentityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.xs,
  },
  managerRemoveButton: {
    marginLeft: 'auto',
    borderWidth: 1,
    borderRadius: borderRadius.round,
    width: moderateScale(26),
    height: moderateScale(26),
    alignItems: 'center',
    justifyContent: 'center',
  },
  nameListText: {
    fontSize: fontSize(11),
    marginBottom: 0,
    flexShrink: 1,
  },
  requestRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    paddingVertical: spacing.sm,
  },
  requestUserInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
    marginRight: spacing.sm,
  },
  requestUser: {
    flex: 1,
    fontSize: fontSize(12),
    fontWeight: '600',
  },
  requestBtns: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  acceptBtn: {
    borderRadius: borderRadius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  rejectBtn: {
    borderRadius: borderRadius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  requestBtnText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: fontSize(11),
  },
  savingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    marginTop: spacing.md,
    paddingVertical: spacing.sm,
  },
  savingText: {
    fontSize: fontSize(12),
    fontWeight: '600',
  },
  deleteChannelButton: {
    marginTop: spacing.sm,
    borderWidth: 1,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
  },
  deleteChannelButtonText: {
    fontSize: fontSize(12),
    fontWeight: '700',
  },
  commentsModalWrap: {
    flex: 1,
  },
  commentsHeader: {
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginTop: spacing.sm,
  },
  commentsTitle: {
    flex: 1,
    fontSize: fontSize(15),
    fontWeight: '700',
    marginRight: spacing.sm,
  },
  commentsList: {
    padding: spacing.sm,
    paddingBottom: spacing.xl,
  },
  commentCard: {
    borderWidth: 1,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
    marginBottom: spacing.sm,
  },
  commentTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  commentUser: {
    fontSize: fontSize(11),
    fontWeight: '700',
  },
  commentText: {
    fontSize: fontSize(12),
    lineHeight: fontSize(17),
  },
  commentComposer: {
    borderTopWidth: 1,
    padding: spacing.sm,
    gap: spacing.sm,
  },
  commentInput: {
    borderWidth: 1,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: fontSize(12),
  },
  sendCommentBtn: {
    borderRadius: borderRadius.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  sendCommentText: {
    color: '#FFFFFF',
    fontSize: fontSize(12),
    fontWeight: '700',
  },
});

