import { StyleSheet, Platform } from 'react-native';
import { fontSize, spacing, moderateScale, wp } from '../../utils/responsive';
import { borderRadius } from '../../theme/designTokens';
import {
  LINE_HEIGHT,
  VOICE_LOCK_THRESHOLD,
} from './constants';

const styles = StyleSheet.create({
  wrapper: {
    borderTopWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingTop: spacing.xs,
  },

  pollComposerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  pollComposerCard: {
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
    maxHeight: '82%',
  },
  pollComposerTitle: {
    fontSize: fontSize(18),
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  pollComposerInput: {
    borderWidth: 1,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    fontSize: fontSize(14),
    marginBottom: spacing.xs,
  },
  pollComposerOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  pollComposerOptionInput: {
    flex: 1,
    marginBottom: spacing.xs,
  },
  pollComposerRemoveButton: {
    width: moderateScale(34),
    height: moderateScale(34),
    borderRadius: borderRadius.md,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xs,
  },
  pollComposerInlineAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
  },
  pollComposerInlineActionText: {
    fontSize: fontSize(13),
    fontWeight: '600',
  },
  pollComposerModeRow: {
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.xs,
  },
  pollComposerModeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.xs,
  },
  pollComposerModeText: {
    fontSize: fontSize(13),
    fontWeight: '500',
    flexShrink: 1,
  },
  pollComposerMaxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
  },
  pollComposerMaxLabel: {
    fontSize: fontSize(12),
    fontWeight: '500',
  },
  pollComposerMaxInput: {
    width: moderateScale(54),
    borderWidth: 1,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.xs,
    textAlign: 'center',
    fontSize: fontSize(13),
    fontWeight: '600',
  },
  pollComposerCorrectWrap: {
    marginTop: spacing.xs,
  },
  pollComposerActions: {
    marginTop: spacing.sm,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  pollComposerActionButton: {
    flex: 1,
    borderWidth: 1,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
  },
  pollComposerActionText: {
    fontSize: fontSize(14),
    fontWeight: '600',
  },

  replyPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    marginBottom: spacing.xs,
    borderRadius: borderRadius.md,
    borderLeftWidth: 3,
  },
  replyContent: { flex: 1 },
  replyLabel: { fontWeight: '600', marginBottom: 2 },
  replyText: { fontWeight: '400' },
  cancelReplyBtn: { padding: spacing.xs },

  imagePreviewRow: {
    marginBottom: spacing.xs,
    paddingHorizontal: spacing.xs,
  },
  imagePreviewWrap: {
    width: moderateScale(80),
    height: moderateScale(80),
    borderRadius: borderRadius.lg,
    overflow: 'hidden',
  },
  imagePreview: {
    width: '100%',
    height: '100%',
  },
  removeImageBtn: {
    position: 'absolute',
    top: moderateScale(4),
    right: moderateScale(4),
  },
  removeImageCircle: {
    width: moderateScale(22),
    height: moderateScale(22),
    borderRadius: moderateScale(11),
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: borderRadius.lg,
  },
  filePreviewRow: {
    marginBottom: spacing.xs,
    paddingHorizontal: spacing.xs,
  },
  filePreviewCard: {
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  filePreviewIconWrap: {
    width: moderateScale(34),
    height: moderateScale(34),
    borderRadius: moderateScale(17),
    justifyContent: 'center',
    alignItems: 'center',
  },
  filePreviewInfo: {
    flex: 1,
  },
  filePreviewName: {
    fontWeight: '600',
  },
  filePreviewMeta: {
    marginTop: 2,
    fontWeight: '500',
  },
  removeFileBtn: {
    padding: 2,
  },
  fileUploadingWrap: {
    minWidth: moderateScale(20),
    alignItems: 'center',
    justifyContent: 'center',
  },

  mentionBox: {
    position: 'absolute',
    bottom: moderateScale(60),
    left: spacing.sm,
    right: spacing.sm,
    borderRadius: borderRadius.lg,
    padding: spacing.xs,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 10,
    maxHeight: moderateScale(180),
  },
  mentionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
  },
  mentionAvatar: {
    width: moderateScale(30),
    height: moderateScale(30),
    borderRadius: moderateScale(15),
    justifyContent: 'center',
    alignItems: 'center',
  },
  mentionAvatarImg: {
    width: moderateScale(30),
    height: moderateScale(30),
    borderRadius: moderateScale(15),
  },
  mentionName: { fontWeight: '500', flex: 1 },

  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  plusButton: {
    width: moderateScale(38),
    height: moderateScale(38),
    borderRadius: moderateScale(19),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: moderateScale(1),
  },
  inputContainer: {
    flex: 1,
    borderRadius: borderRadius.xl,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: Platform.OS === 'ios' ? spacing.sm : spacing.xs,
    justifyContent: 'center',
  },
  textInput: {
    lineHeight: LINE_HEIGHT,
    minHeight: moderateScale(22),
    textAlignVertical: 'center',
  },
  sendButton: {
    width: moderateScale(38),
    height: moderateScale(38),
    borderRadius: moderateScale(19),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: moderateScale(1),
  },
  voiceButtonWrap: {
    position: 'relative',
  },
  voiceLockPopup: {
    position: 'absolute',
    left: '50%',
    top: -VOICE_LOCK_THRESHOLD,
    marginLeft: moderateScale(-16),
    width: moderateScale(32),
    height: moderateScale(32),
    borderRadius: moderateScale(16),
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  voiceLockPopupActive: {
    backgroundColor: '#EF4444',
    borderColor: '#EF4444',
  },
  voiceRecordingBar: {
    marginTop: spacing.xs,
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    gap: spacing.xs,
  },
  voiceRecordingInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  voiceRecordingTime: {
    fontWeight: '700',
    fontSize: fontSize(13),
  },
  voiceRecordingHint: {
    fontWeight: '500',
    fontSize: fontSize(12),
  },
  voiceHintsContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.xs,
  },
  slideCancelPill: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.xs / 2,
    paddingHorizontal: spacing.xs,
    gap: spacing.xs / 2,
  },
  slideCancelText: {
    fontWeight: '600',
    fontSize: fontSize(11),
  },
  voiceWaveformRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs / 2,
    minHeight: moderateScale(20),
  },
  voiceWaveBar: {
    width: moderateScale(3),
    borderRadius: moderateScale(2),
  },
  voiceRecordingActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing.sm,
  },
  voiceActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  voiceActionText: {
    fontWeight: '600',
    fontSize: fontSize(12),
  },

  actionSheet: {
    marginTop: spacing.sm,
    borderRadius: borderRadius.xl,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
  },
  actionItem: {
    alignItems: 'center',
    width: wp(18),
    marginBottom: spacing.sm,
  },
  actionIconCircle: {
    width: moderateScale(50),
    height: moderateScale(50),
    borderRadius: moderateScale(25),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  actionLabel: {
    fontWeight: '500',
    textAlign: 'center',
  },

  locationOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
  },
  locationModal: {
    width: '100%',
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
  },
  locationTitle: {
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: spacing.md,
  },
  locationMapWrap: {
    width: '100%',
    height: moderateScale(180),
    borderRadius: borderRadius.lg,
    overflow: 'hidden',
    marginBottom: spacing.md,
    backgroundColor: 'rgba(0,0,0,0.05)',
  },
  locationMap: { width: '100%', height: '100%' },
  locationCoords: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  locationCoordsText: { fontWeight: '500' },
  locationConfirm: { textAlign: 'center', marginBottom: spacing.lg },
  locationBtns: { flexDirection: 'row', gap: spacing.md },
  locationCancelBtn: {
    flex: 1,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationCancelText: { fontWeight: '600' },
  locationSendBtn: {
    flex: 1,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  locationSendText: { fontWeight: '600', color: '#FFFFFF' },
});

export default styles;
